build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
              override:
                - php-scrutinizer-run --enable-security-analysis
                - js-scrutinizer-run

    environment:
      php: 7.3.0
      mysql: 5.5

filter:
    excluded_paths:
      - 'js/highcharts/*'
      - 'js/jquery*'

imports:
    - javascript
    - php
