# Jekyll configuration
repository: rello/analytics
theme: jekyll-theme-cayman
timezone: Europe/Berlin
name: "Analytics"
title: "Analytics"
description: "Connect data from different sources in one place. <br>Enable flexibile reports and enjoy seamless Nextcloud integration."
url: "https://rello.github.io/audioplayer"
author: "Marcel Scherello"
