# Jekyll configuration
repository: rello/analytics
theme: jekyll-theme-architect
timezone: Europe/Berlin
name: "Analytics"
title: "Analytics"
description: "Open source data warehouse and reporting for Nextcloud"
url: "https://rello.github.io/audioplayer"
author: "Marcel Scherello"
