# Jekyll configuration
repository: rello/data
theme: jekyll-theme-cayman
timezone: Europe/Berlin
name: "Audio Player - ID3 Editor"
title: "Audio Player Editor"
description: "Audio Player for Nextcloud and ownCloud"
url: "https://github.com/rello/data"
author: "Marcel Scherello"
