# Jekyll configuration
repository: rello/analytics
theme: jekyll-theme-minimal
timezone: Europe/Berlin
name: "Analytics"
title: "Analytics"
description: "Connect data from different sources in one place. <br>Enable flexibile reports and enjoy seamless Nextcloud integration.<br>Visualize and share anything, from financial analysis to IoT logs."
url: "https://rello.github.io/audioplayer"
author: "Marcel Scherello"
